import { useState, useEffect, useRef } from 'react'
import CategoryPicker from '../../../components/CategoryPicker'
import { CONDITIONS, CONDITION_LABELS, WEIGHT_UNITS, WEIGHT_UNIT_LABELS, SCRAP_MATERIAL_TYPES, SCRAP_METAL_TYPES, SCRAP_SHAPES } from '../../../lib/constants'
import { ALLOWED_IMAGE_TYPES, MAX_IMAGE_BYTES, getListingImageUrl } from '../api/listingImages'
import '../../../components/EntityForm.css'

const MAX_PHOTOS = 6

// Suggested spec labels for machinery sell listings — purely a description-writing
// aid (description stays free text; no structured specs column exists).
const SPEC_SUGGESTIONS = ['Make', 'Model', 'Year', 'Height', 'Width', 'Length', 'Weight', 'Power']

function specLineRegex(label) {
  return new RegExp(`^${label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}:.*$`, 'mi')
}

// material_type is stored as the specific metal (e.g. "Copper"), not the
// literal word "Metal" — reverse it into {material_type, metal_type} so the
// two dropdowns can be prefilled on edit.
function deriveMaterialFields(rawMaterialType) {
  if (SCRAP_METAL_TYPES.includes(rawMaterialType)) {
    return { material_type: 'Metal', metal_type: rawMaterialType }
  }
  if (SCRAP_MATERIAL_TYPES.includes(rawMaterialType)) {
    return { material_type: rawMaterialType, metal_type: '' }
  }
  return { material_type: '', metal_type: '' }
}

const EMPTY_FORM = {
  machine_category_id: '',
  title: '',
  description: '',
  condition: '',
  price: '',
  quantity: '1',
  city: '',
  state: '',
  material_type: '',
  metal_type: '',
  shape: '',
  weight: '',
  weight_unit: 'KG'
}

export const SELL_COPY = {
  titleLabel: 'Title *',
  titlePlaceholder: 'e.g. CNC Milling Machine, VMC 3-axis',
  descriptionLabel: 'Description',
  descriptionPlaceholder: 'Specs, model, year, condition notes…',
  priceLabel: 'Price (INR)',
  pricePlaceholder: 'Contact for price',
  quantityLabel: 'Quantity',
  conditionLabel: 'Condition',
  conditionNoneLabel: 'Not specified',
  conditionSuffix: '',
  savingLabel: 'Saving…'
}

export const REQUIREMENT_COPY = {
  intro: "Tell sellers what you need — they'll reach out with an offer.",
  titleLabel: 'What are you looking for? *',
  titlePlaceholder: 'e.g. Used CNC lathe, under 5 years old',
  descriptionLabel: 'More details',
  descriptionPlaceholder: 'Specs, must-haves, timeline…',
  priceLabel: 'Budget (INR)',
  pricePlaceholder: 'Open to offers',
  quantityLabel: 'Quantity needed',
  conditionLabel: 'Preferred condition',
  conditionNoneLabel: 'Either is fine',
  conditionSuffix: ' only',
  savingLabel: 'Posting…'
}

function ListingForm({ section = 'MACHINERY', intent, copy, initialValues, existingImages, onSubmit, onCancel, submitLabel, saving, error }) {
  const [form, setForm] = useState(() => {
    const merged = { ...EMPTY_FORM, ...initialValues }
    if (initialValues?.material_type) {
      Object.assign(merged, deriveMaterialFields(initialValues.material_type))
    }
    if (initialValues?.shape && !SCRAP_SHAPES.includes(initialValues.shape)) {
      merged.shape = ''
    }
    return merged
  })
  const [keptImages, setKeptImages] = useState(existingImages || [])
  const [removedImageIds, setRemovedImageIds] = useState([])
  const [newImages, setNewImages] = useState([]) // [{ file, previewUrl }]
  const [photoError, setPhotoError] = useState('')
  const [customSpecLabel, setCustomSpecLabel] = useState('')
  const [addingCustomSpec, setAddingCustomSpec] = useState(false)
  // Scrap title defaults to an auto-generated string built from material/shape;
  // stops regenerating once the user types into the title field directly.
  const [titleAutoGenerated, setTitleAutoGenerated] = useState(() => section === 'SCRAP' && !initialValues?.title)
  const fileInputRef = useRef(null)
  const descriptionRef = useRef(null)

  const showSpecSuggestions = section === 'MACHINERY' && intent === 'SELL'

  useEffect(() => {
    if (section !== 'SCRAP' || !titleAutoGenerated) return
    const effectiveMaterial = form.material_type === 'Metal' ? form.metal_type : form.material_type
    const generated = [effectiveMaterial, form.shape].filter(Boolean).join(' ')
    setForm(prev => ({ ...prev, title: generated ? `${generated} Scrap` : '' }))
  }, [section, titleAutoGenerated, form.material_type, form.metal_type, form.shape])

  const handleTitleChange = (e) => {
    setTitleAutoGenerated(false)
    setForm(prev => ({ ...prev, title: e.target.value }))
  }

  const toggleSpecLine = (label) => {
    if (!label.trim()) return
    setForm(prev => {
      const regex = specLineRegex(label)
      if (regex.test(prev.description)) {
        const description = prev.description.replace(regex, '').replace(/\n{2,}/g, '\n').trim()
        return { ...prev, description }
      }
      const line = `${label}: `
      const description = prev.description.trim() ? `${prev.description.trim()}\n${line}` : line
      return { ...prev, description }
    })
    requestAnimationFrame(() => {
      const el = descriptionRef.current
      if (el) {
        el.focus()
        el.selectionStart = el.selectionEnd = el.value.length
      }
    })
  }

  const handleAddCustomSpec = () => {
    const label = customSpecLabel.trim()
    if (!label) {
      setAddingCustomSpec(false)
      return
    }
    toggleSpecLine(label)
    setCustomSpecLabel('')
    setAddingCustomSpec(false)
  }

  // Revoke object URLs for locally-picked photos when they're replaced/unmounted.
  useEffect(() => {
    return () => newImages.forEach(image => URL.revokeObjectURL(image.previewUrl))
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const totalPhotoCount = keptImages.length + newImages.length

  const handleChange = (field) => (e) => {
    setForm(prev => ({ ...prev, [field]: e.target.value }))
  }

  const handleFilesSelected = (e) => {
    const files = Array.from(e.target.files || [])
    e.target.value = '' // allow re-selecting the same file later
    if (files.length === 0) return

    setPhotoError('')

    const room = MAX_PHOTOS - totalPhotoCount
    if (room <= 0) {
      setPhotoError(`You can add up to ${MAX_PHOTOS} photos`)
      return
    }

    const accepted = []
    for (const file of files.slice(0, room)) {
      if (!ALLOWED_IMAGE_TYPES.includes(file.type)) {
        setPhotoError('Only JPEG, PNG, or WEBP images are allowed')
        continue
      }
      if (file.size > MAX_IMAGE_BYTES) {
        setPhotoError('Each image must be smaller than 5MB')
        continue
      }
      accepted.push({ file, previewUrl: URL.createObjectURL(file) })
    }

    if (accepted.length > 0) {
      setNewImages(prev => [...prev, ...accepted])
    }
  }

  const removeKeptImage = (imageId) => {
    setKeptImages(prev => prev.filter(image => image.id !== imageId))
    setRemovedImageIds(prev => [...prev, imageId])
  }

  const removeNewImage = (previewUrl) => {
    setNewImages(prev => prev.filter(image => {
      if (image.previewUrl === previewUrl) {
        URL.revokeObjectURL(image.previewUrl)
        return false
      }
      return true
    }))
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    onSubmit({
      intent,
      section,
      machine_category_id: section === 'SCRAP' ? null : (form.machine_category_id || null),
      title: form.title.trim(),
      description: form.description.trim() || null,
      condition: section === 'SCRAP' ? null : (form.condition || null),
      price: form.price === '' ? null : parseFloat(form.price),
      quantity: form.quantity === '' ? 1 : parseInt(form.quantity, 10),
      city: form.city.trim() || null,
      state: form.state.trim() || null,
      material_type: section === 'SCRAP' ? ((form.material_type === 'Metal' ? form.metal_type : form.material_type) || null) : null,
      shape: section === 'SCRAP' ? (form.shape || null) : null,
      weight: section === 'SCRAP' && form.weight !== '' ? parseFloat(form.weight) : null,
      weight_unit: section === 'SCRAP' ? (form.weight_unit || null) : null
    }, {
      removedImageIds,
      newFiles: newImages.map(image => image.file),
      keptImageCount: keptImages.length
    })
  }

  return (
    <form onSubmit={handleSubmit} className="entity-form">
      {error && <div className="banner">{error}</div>}

      {copy.intro && <p className="entity-form__intro">{copy.intro}</p>}

      {section === 'MACHINERY' && (
        <CategoryPicker
          value={form.machine_category_id}
          onChange={(id) => setForm(prev => ({ ...prev, machine_category_id: id }))}
        />
      )}

      {section === 'TOOLS_ACCESSORIES' && (
        <CategoryPicker
          value={form.machine_category_id}
          onChange={(id) => setForm(prev => ({ ...prev, machine_category_id: id }))}
          required={false}
          label="Related machine category"
        />
      )}

      {section === 'SCRAP' && (
        <>
          <div className="field__row">
            <div className="field">
              <label className="field__label" htmlFor="material_type">Material Type</label>
              <select
                id="material_type"
                value={form.material_type}
                onChange={(e) => setForm(prev => ({ ...prev, material_type: e.target.value, metal_type: '' }))}
              >
                <option value="">Select material type</option>
                {SCRAP_MATERIAL_TYPES.map(type => (
                  <option key={type} value={type}>{type}</option>
                ))}
              </select>
            </div>

            <div className="field">
              <label className="field__label" htmlFor="shape">Shape</label>
              <select
                id="shape"
                value={form.shape}
                onChange={handleChange('shape')}
              >
                <option value="">Select shape</option>
                {SCRAP_SHAPES.map(shape => (
                  <option key={shape} value={shape}>{shape}</option>
                ))}
              </select>
            </div>
          </div>

          {form.material_type === 'Metal' && (
            <div className="field">
              <label className="field__label" htmlFor="metal_type">Metal Type</label>
              <select
                id="metal_type"
                value={form.metal_type}
                onChange={handleChange('metal_type')}
              >
                <option value="">Select metal type</option>
                {SCRAP_METAL_TYPES.map(metal => (
                  <option key={metal} value={metal}>{metal}</option>
                ))}
              </select>
            </div>
          )}

          <div className="field">
            <label className="field__label" htmlFor="weight">Weight</label>
            <input
              id="weight"
              type="number"
              className="input--mono"
              value={form.weight}
              onChange={handleChange('weight')}
              placeholder="0.00"
              min="0"
              step="0.01"
            />
          </div>

          <div className="field">
            <span className="field__label">Weight Unit</span>
            <div className="entity-form__chip-toggle">
              {WEIGHT_UNITS.map(unit => (
                <button
                  type="button"
                  key={unit}
                  className={`entity-form__chip ${form.weight_unit === unit ? 'entity-form__chip--active' : ''}`}
                  onClick={() => setForm(prev => ({ ...prev, weight_unit: unit }))}
                >
                  {WEIGHT_UNIT_LABELS[unit]}
                </button>
              ))}
            </div>
          </div>
        </>
      )}

      <div className="field">
        <span className="field__label">Photos</span>
        <div className="entity-form__photos">
          {keptImages.map(image => (
            <div className="entity-form__photo" key={image.id}>
              <img src={getListingImageUrl(image.storage_path)} alt="" />
              <button
                type="button"
                className="entity-form__photo-remove"
                aria-label="Remove photo"
                onClick={() => removeKeptImage(image.id)}
              >
                ×
              </button>
            </div>
          ))}
          {newImages.map(image => (
            <div className="entity-form__photo" key={image.previewUrl}>
              <img src={image.previewUrl} alt="" />
              <button
                type="button"
                className="entity-form__photo-remove"
                aria-label="Remove photo"
                onClick={() => removeNewImage(image.previewUrl)}
              >
                ×
              </button>
            </div>
          ))}
          {totalPhotoCount < MAX_PHOTOS && (
            <button
              type="button"
              className="entity-form__photo-add"
              onClick={() => fileInputRef.current?.click()}
            >
              + Add
            </button>
          )}
        </div>
        <input
          ref={fileInputRef}
          type="file"
          accept="image/jpeg,image/png,image/webp"
          multiple
          hidden
          onChange={handleFilesSelected}
        />
        {photoError && <p className="entity-form__photo-error">{photoError}</p>}
      </div>

      <div className="field">
        <label className="field__label" htmlFor="title">{copy.titleLabel}</label>
        <input
          id="title"
          type="text"
          value={form.title}
          onChange={section === 'SCRAP' ? handleTitleChange : handleChange('title')}
          placeholder={copy.titlePlaceholder}
          maxLength={255}
          required
        />
        {section === 'SCRAP' && titleAutoGenerated && (
          <p className="field__hint">Auto-filled from material type and shape — edit if you'd like.</p>
        )}
      </div>

      <div className="field">
        <label className="field__label" htmlFor="description">{copy.descriptionLabel}</label>
        <textarea
          id="description"
          ref={descriptionRef}
          value={form.description}
          onChange={handleChange('description')}
          placeholder={copy.descriptionPlaceholder}
          rows={5}
        />
        {showSpecSuggestions && (
          <div className="entity-form__spec-suggestions">
            <span className="entity-form__spec-hint">Add specs (optional) — tap to insert, then fill in the value</span>
            <div className="entity-form__chip-toggle">
              {SPEC_SUGGESTIONS.map(label => (
                <button
                  type="button"
                  key={label}
                  className={`entity-form__chip ${specLineRegex(label).test(form.description) ? 'entity-form__chip--active' : ''}`}
                  onClick={() => toggleSpecLine(label)}
                >
                  {label}
                </button>
              ))}
              {addingCustomSpec ? (
                <span className="entity-form__spec-custom-input">
                  <input
                    type="text"
                    autoFocus
                    value={customSpecLabel}
                    onChange={(e) => setCustomSpecLabel(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') {
                        e.preventDefault()
                        handleAddCustomSpec()
                      }
                      if (e.key === 'Escape') {
                        setAddingCustomSpec(false)
                        setCustomSpecLabel('')
                      }
                    }}
                    onBlur={handleAddCustomSpec}
                    placeholder="Spec name"
                    maxLength={40}
                  />
                </span>
              ) : (
                <button
                  type="button"
                  className="entity-form__chip"
                  onClick={() => setAddingCustomSpec(true)}
                >
                  + Other spec
                </button>
              )}
            </div>
          </div>
        )}
      </div>

      <div className="field__row">
        <div className="field">
          <label className="field__label" htmlFor="price">{copy.priceLabel}</label>
          <input
            id="price"
            type="number"
            className="input--mono"
            value={form.price}
            onChange={handleChange('price')}
            placeholder={copy.pricePlaceholder}
            min="0"
            step="0.01"
          />
        </div>

        <div className="field">
          <label className="field__label" htmlFor="quantity">{copy.quantityLabel}</label>
          <input
            id="quantity"
            type="number"
            className="input--mono"
            value={form.quantity}
            onChange={handleChange('quantity')}
            min="1"
            step="1"
          />
        </div>
      </div>

      {section !== 'SCRAP' && (
        <div className="field">
          <span className="field__label">{copy.conditionLabel}</span>
          <div className="entity-form__chip-toggle">
            <button
              type="button"
              className={`entity-form__chip ${form.condition === '' ? 'entity-form__chip--active' : ''}`}
              onClick={() => setForm(prev => ({ ...prev, condition: '' }))}
            >
              {copy.conditionNoneLabel}
            </button>
            {CONDITIONS.map(condition => (
              <button
                type="button"
                key={condition}
                className={`entity-form__chip ${form.condition === condition ? 'entity-form__chip--active' : ''}`}
                onClick={() => setForm(prev => ({ ...prev, condition }))}
              >
                {CONDITION_LABELS[condition]}{copy.conditionSuffix}
              </button>
            ))}
          </div>
        </div>
      )}

      <div className="field__row">
        <div className="field">
          <label className="field__label" htmlFor="city">City</label>
          <input id="city" type="text" value={form.city} onChange={handleChange('city')} placeholder="e.g. Coimbatore" />
        </div>
        <div className="field">
          <label className="field__label" htmlFor="state">State</label>
          <input id="state" type="text" value={form.state} onChange={handleChange('state')} placeholder="e.g. Tamil Nadu" />
        </div>
      </div>

      <div className="entity-form__actions">
        <button type="button" className="btn btn--ghost btn--block" onClick={onCancel} disabled={saving}>
          Cancel
        </button>
        <button type="submit" className="btn btn--primary btn--block" disabled={saving}>
          {saving ? copy.savingLabel : submitLabel}
        </button>
      </div>
    </form>
  )
}

export default ListingForm
